### ISSUE TITLE
Upgrade DotNetCore DI samples to 3.0?

### ISSUE THREAD

**Issue by robertmclaws** [ProfessionalCSharp/MoreSamples#46]
Hey Christian! It would be really great if you could update these samples for .NET Core 3.0. I'm trying to figure out how to get the IConfiguration out of the new default HostBuilder() options and am having some trouble getting my head around it.

Thanks!

**Comment by christiannagel** [comment]
@robertmclaws, the code sample update is now in the dotnetcore3DI branch. It will move to the master branch when the blog article update is ready.
